
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  approval-job:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 3f57a526-f069-11ec-a326-42010a83ae55
      disallowLaunchByUser: false
      instructions: some
      approvalInputs: |
        in1:
          type: string
          required: true
          description: One of the required approver inputs
        in2:
          type: number
          description: a numeric input
        in3:
          type: choice
          options:
            - op1
            - op2
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - approval-job
