apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
        - approval-job
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  approval-job:
    needs:
      - job1
    environment: testnico
    steps:
      - with:
          registry-url: test
          source-repository-name: asd
          source-tag: asd
        uses: totototo
