apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: wf with array trigger
on:
  - push
  - schedule
  - pull_request
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh